using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Messaging;
using FontExamine.Services;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Text;
using System.Text.Json;

namespace FontExamine.Model
{
    public partial class SymbolIconDefinitionsProject:ObservableObject
    {
        
        [ObservableProperty]
        private string _activeDefinitionName;
        [ObservableProperty]
        private ObservableCollection<SymbolIconDefinitions> _definitions=new();

        public SymbolIconDefinitionsProject()
        {
            WeakReferenceMessenger.Default.Register<ProjectRenamedEventArgs>(this, HandleProjectRenamed);
        }

        private void HandleProjectRenamed(object recipient, ProjectRenamedEventArgs message)
        {
            if(message.OldName == ActiveDefinitionName)
            {
                ActiveDefinitionName = message.NewName;
            }
        }

        internal void SaveDefinitions(string projectFilename)
        {
            var options = new JsonSerializerOptions() { WriteIndented = true };
            var stream = File.Create(projectFilename);
            JsonSerializer.Serialize(stream, this, options);
            stream.Close();
        }
        internal static SymbolIconDefinitionsProject LoadDefinitions(string projectName)
        {
            if (File.Exists(projectName))
            {
                GlyphDocument.LoadingDocument = true;
                var contents = File.ReadAllText(projectName);
                var result= JsonSerializer.Deserialize<SymbolIconDefinitionsProject>(contents) ?? new SymbolIconDefinitionsProject();
                GlyphDocument.LoadingDocument = false;
                return result;
            }
            else
                return new SymbolIconDefinitionsProject();
        }
        internal string GenerateStaticClass(string definitionName)
        {
            if(Definitions.FirstOrDefault(x => x.Name == definitionName) is SymbolIconDefinitions definitions)
            {
                //var code = new StringBuilder();
                //code.AppendLine("// This code is generated based on the selected icons in the project.");
                //code.AppendLine("// It defines an enum for the icons and a dictionary to map the enum values to their corresponding Unicode characters.");
                //code.AppendLine($"// this code is generated by a tool, it can be automatically regenerated.  Generated :{DateTime.Now:f}");
                //if (includeNamespaceDeclaration) 
                //    code.AppendLine($"namespace {projectNamespace}.Markup;");
                //code.AppendLine($"public static class {symbolName}GlyphHelper");
                //code.AppendLine("{");
                //var tabcount = 1;
                //var tabs = new string('\t', tabcount);
                var enumContent=CodeGeneration.GenerateEnums($"{definitions.SymbolName}Symbols", (from d in definitions.DefinedGlyphs select d.GlyphName).Distinct().Order());
                //code.AppendLine("{");
                //var names = (from d in definitions.DefinedGlyphs select d.GlyphName).Distinct();
                //code.AppendLine(string.Join(",\n", names));
                //code.AppendLine("}");
                // Static Dictionary Generation
                var dictionaryContent=CodeGeneration.GenerateDictionaryDefinition("Symbols", $"{definitions.SymbolName}Symbols", definitions.DefinedGlyphs.OrderBy(g=>g.GlyphName).Select(d => d.DictionaryEntry(definitions.SymbolName)));
                //code.AppendLine("public static readonly Dictionary<SegoeSymbols,string> Symbols=new()");
                //code.AppendLine("{");
                //code.AppendLine(string.Join(",\n", definitions.DefinedGlyphs.Select(d=>d.DictionaryEntry)));
                //code.AppendLine("};");
                //code.AppendLine("} // End of code generation");
                return CodeGeneration.GenerateStaticClass(definitions.SymbolName,enumContent,dictionaryContent,definitions.NamespaceName,definitions.DeclareNamespace);
            }
            return string.Empty;
        }
    }
}
