using System;
using System.Collections.Generic;
using System.Text;

namespace FontExamine.Services
{
    internal class CodeGeneration
    {
        /// <summary>
        /// Generates C# source code for a static class that defines an icon enumeration and a dictionary mapping enum
        /// values to Unicode characters.
        /// </summary>
        /// <remarks>This method is intended for use in code generation scenarios where icon sets and
        /// their Unicode mappings need to be programmatically defined. The generated code can be regenerated as needed
        /// to reflect changes in the icon selection.</remarks>
        /// <param name="symbolName">The name of the static class to be generated. This value is used as the class identifier in the generated
        /// code.</param>
        /// <param name="enumContent">A string containing the C# enum definition for the icons. This should represent the set of icon identifiers
        /// to include in the generated class.</param>
        /// <param name="dictionaryContent">A string containing the C# dictionary definition that maps enum values to their corresponding Unicode
        /// characters. This enables lookup of icon glyphs by enum value.</param>
        /// <param name="namespaceName">The namespace under which the static class will be defined. Defaults to "FontDefine" if not specified.</param>
        /// <param name="includeNamespace">Indicates whether to include the namespace declaration in the generated code. Set to <see langword="true"/>
        /// to include the namespace; otherwise, <see langword="false"/>.</param>
        /// <returns>A string containing the generated C# code for the static class, including the enum and dictionary
        /// definitions.</returns>
        internal static string GenerateStaticClass(string symbolName,string enumContent,string dictionaryContent,string namespaceName="FontDefine",bool includeNamespace=false)
        {
            var code = new StringBuilder();
            code.AppendLine("// This code is generated based on the selected icons in the project.");
            code.AppendLine("// It defines an enum for the icons and a dictionary to map the enum values to their corresponding Unicode characters.");
            code.AppendLine($"// this code is generated by a tool, it can be automatically regenerated.  Generated :{DateTime.Now:f}");
            if (includeNamespace)
                code.AppendLine($"namespace {namespaceName}.Markup;");
            code.AppendLine($"public static class {symbolName}GlyphHelper");
            code.AppendLine("{");
            code.AppendLine(enumContent);
            code.Append(dictionaryContent);
            code.AppendLine("}");
            return code.ToString();

        }
        /// <summary>
        /// Generates a string containing the C# code for a public enum with the specified name and members.
        /// </summary>
        /// <remarks>The generated code is suitable for inclusion in C# source files. Ensure that the
        /// provided enum member names are valid and do not conflict with each other or reserved keywords.</remarks>
        /// <param name="enumName">The name of the enum to be generated. Must be a valid C# identifier.</param>
        /// <param name="enumValues">An enumerable collection of strings representing the names of the enum members. Each value must be a valid
        /// C# identifier and should be unique within the collection.</param>
        /// <returns>A string that defines a public enum in C# syntax, including the specified name and member values.</returns>
        internal static string GenerateEnums(string enumName,IEnumerable<string> enumValues)
        {
            var code = new StringBuilder();
            code.AppendLine($"public enum {enumName}{{");
            code.AppendLine(string.Join(",\n", enumValues));
            code.AppendLine("}");
            return code.ToString();
        }
        /// <summary>
        /// Generates a C# code string that defines a static readonly dictionary with the specified name, key type, and
        /// entries.
        /// </summary>
        /// <remarks>This method is useful for code generation scenarios where dictionary definitions need
        /// to be created dynamically. The returned string can be inserted directly into source code files to define
        /// constant dictionaries.</remarks>
        /// <param name="dictionaryName">The name to assign to the generated dictionary in the code definition.</param>
        /// <param name="keyTypeName">The type name to use for the dictionary's keys in the generated code.</param>
        /// <param name="dictionaryEntries">An enumerable collection of string representations of dictionary entries to include in the definition.</param>
        /// <returns>A string containing the complete C# syntax for a static readonly dictionary declaration with the specified
        /// parameters.</returns>
        internal static string GenerateDictionaryDefinition(string dictionaryName,string keyTypeName,IEnumerable<string> dictionaryEntries)
        {
            var code = new StringBuilder();
            code.AppendLine($"public static readonly Dictionary<{keyTypeName},string> {dictionaryName}=new()");
            code.AppendLine("{");
            code.Append(string.Join(",\n",dictionaryEntries));
            code.AppendLine("};");
            code.AppendLine($"// End of dictionary definition for {dictionaryName}");
            return code.ToString();
        }
    }
}
