<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyTitle>FontIconExamine</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Markup\GlyphGlue - Copy.cs" />
    <Compile Remove="Markup\LinkGlyph - Copy.cs" />
    <Compile Remove="Markup\SegoeSymbolMarkupExtension.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Markup\GlyphGlue.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GlyphGlue.tt</DependentUpon>
    </None>
    <None Include="Markup\LinkGlyph SegoeFluent.cs">
      <DependentUpon>LinkGlyph.tt</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </None>
    <None Include="Markup\LinkGlyph.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LinkGlyph.tt</DependentUpon>
    </None>
    <None Include="Markup\LinkGlyphFluent.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LinkGlyphFluent.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Markup\GlyphGlue Fluent.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GlyphGlue Fluent.tt</DependentUpon>
    </Compile>
    <Compile Update="Markup\GlyphGlue.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GlyphGlue.tt</DependentUpon>
    </Compile>
    <Compile Update="Markup\LinkGlyph SegoeFluent.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LinkGlyph SegoeFluent.tt</DependentUpon>
    </Compile>
    <Compile Update="Markup\LinkGlyph.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LinkGlyph.tt</DependentUpon>
    </Compile>
    <Compile Update="Markup\LinkGlyphFluent.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LinkGlyphFluent.tt</DependentUpon>
    </Compile>
    <Compile Update="Settings1.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings1.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Markup\GlyphGlue Fluent.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>GlyphGlue Fluent.cs</LastGenOutput>
    </None>
    <None Update="Markup\GlyphGlue.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>GlyphGlue.cs</LastGenOutput>
    </None>
    <None Update="Markup\LinkGlyph SegoeFluent.tt">
      <LastGenOutput>LinkGlyph SegoeFluent.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="Markup\LinkGlyph.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>LinkGlyph.cs</LastGenOutput>
    </None>
    <None Update="Markup\LinkGlyphFluent.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>LinkGlyphFluent.cs</LastGenOutput>
    </None>
    <None Update="Settings1.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings1.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
